version: 2
name: Sample pipeline for github action
runs_on:
  image: ubuntu:latest
  pull: true

variables:
  var1: goodnight
  var2: planet

jobs:
  main:
  - echo ${{var1}} ${{var2}} from github action!
